version: '3.8'
services:
# MongoDB service
mongodb:
image: mongo:5.0

container_name: yolo-mongodb

restart: unless-stopped

ports:
- "27017:27017"
environment:
MONGO_INITDB_ROOT_USERNAME: admin
MONGO_INITDB_ROOT_PASSWORD: secret
MONGO_INITDB_DATABASE: yolo

volumes:
- mongodb-data:/data/db

networks:
- yolo-network