version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:5.0
    container_name: yolo-mongodb
    ports:
    
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: yolo
    volumes:
      - mongodb-data:/data/db
    networks:
      - yolo-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yolo-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://admin:secret@mongodb:27017/yolo?authSource=admin
    depends_on:
      - mongodb
    networks:
      - yolo-network
  
  # Frontend service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: yolo-client
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - yolo-network

# Volumes at root level - NOT indented under services
volumes:
  mongodb-data:

# Networks at root level
networks:
  yolo-network:
    driver: bridge