---
- name: Deploy YOLO Application
  hosts: localhost
  connection: local
  become: yes
  
  vars_files:
    - group_vars/all/main.yml
  
  pre_tasks:
    - name: Display deployment info
      debug:
        msg:
          - "Starting YOLO Deployment"
          - "Frontend Port: {{ frontend_port }}"
          - "Backend Port: {{ backend_port }}"
          - "MongoDB Port: {{ mongodb_port }}"
  
  roles:
    - common
    - mongodb
    - backend
    - frontend
    
  post_tasks:
    - name: Deployment summary
      debug:
        msg:
          - "✅ Deployment successful!"
          - "Frontend URL: http://localhost:{{ frontend_port }}"
          - "Backend URL: http://localhost:{{ backend_port }}"
          - "MongoDB URL: mongodb://{{ mongodb_user }}:{{ mongodb_pass }}@localhost:{{ mongodb_port }}/{{ mongodb_database }}"