---
- name: Build frontend image
  docker_image:
    name: yolo-client
    build:
      path: /vagrant/client
    source: build

- name: Run frontend
  docker_container:
    name: yolo-client
    image: yolo-client
    state: started
    networks:
      - name: yolo-network
    ports:
      - "3333:80"
    env:
      REACT_APP_API_URL: http://localhost:5555

- name: Wait for frontend
  wait_for:
    port: 3333
    delay: 5
