---
- name: Pull frontend image from Docker Hub
  docker_image:
    name: joseden/yolo-frontend
    source: pull

- name: Run frontend container
  docker_container:
    name: brian-yolo-frontend
    image: joseden/yolo-client
    networks:
      - name: app-net
    ports:
      - "3000:80"
    restart_policy: always
  become: yes 