---
# Backend Role: Run the API server
# This pulls and runs the backend from Docker Hub

- name: Ensure Docker network exists
  docker_network:
    name: app-net

- name: Pull backend image from Docker Hub
  docker_image:
    name: joseden/yolo-backend
    source: pull

- name: Run backend container
  docker_container:
    name: brian-yolo-backend
    image: joseden/yolo-backend
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    restart_policy: always
  become: yes