---
- name: Create Docker network
  docker_network:
    name: "{{ docker_network }}"
- name: Run MongoDB container
  docker_container:
    name: "{{ app_name }}-mongodb"
    image: mongo:5.0
    state: started
    networks:
      - name: "{{ docker_network }}"
    ports:
      - "27017:27017"
- name: Wait for MongoDB
  wait_for:
    port: 27017
    delay: 5
