---
- name: Deploy MongoDB
  block:
    - name: Pull MongoDB image
      community.docker.docker_image:
        name: "{{ mongodb_image }}"
        source: pull
        
    - name: Run MongoDB container
      community.docker.docker_container:
        name: "{{ mongodb_container }}"
        image: "{{ mongodb_image }}"
        state: started
        restart_policy: always
        networks:
          - name: "{{ network_name }}"
        ports:
          - "{{ mongodb_port }}:27017"
        env:
          MONGO_INITDB_ROOT_USERNAME: "{{ mongodb_user }}"
          MONGO_INITDB_ROOT_PASSWORD: "{{ mongodb_pass }}"
          
    - name: Wait for MongoDB
      wait_for:
        port: "{{ mongodb_port }}"
        delay: 5
        timeout: 60
  tags: ['mongodb', 'database']