---
- name: Run MongoDB
  docker_container:
    name: yolo-mongodb
    image: mongo:5.0
    state: started
    networks:
      - name: yolo-network
    ports:
      - "27777:27017"
    env:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: yolo
    volumes:
      - mongodb-data:/data/db

- name: Wait for MongoDB
  wait_for:
    port: 27777
    delay: 5
