---
- name: Build backend image
  docker_image:
    name: "{{ app_name }}/backend"
    build:
      path: "{{ project_dir }}/backend"
    source: build
    force_source: yes
- name: Run backend container
  docker_container:
    name: "{{ app_name }}-backend"
    image: "{{ app_name }}/backend"
    state: started
    networks:
      - name: "{{ docker_network }}"
    ports:
      - "5000:5000"
    env:
      MONGODB_URI: "mongodb://{{ app_name }}-mongodb:27017/yolodb"
