---
- name: Pull backend image
  docker_image:
    name: joseden/yolo-backend
    source: pull

- name: Run backend container
  docker_container:
    name: brian-yolo-backend
    image: joseden/yolo-backend
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    restart_policy: unless-stopped
    env:
      MONGO_URI: mongodb://admin:secret@app-mongo:27017/yolo?authSource=admin