---
- name: Build backend image
  docker_image:
    name: yolo-backend
    build:
      path: /vagrant/backend
    source: build

- name: Run backend
  docker_container:
    name: yolo-backend
    image: yolo-backend
    state: started
    networks:
      - name: yolo-network
    ports:
      - "5555:5000"
    env:
      MONGO_URI: mongodb://admin:secret@yolo-mongodb:27017/yolo?authSource=admin

- name: Wait for backend
  wait_for:
    port: 5555
    delay: 5
