apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: yolo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: joseden/yolo-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb://mongodb:27017/yolodb"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: yolo-app
spec:
  selector:
    app: backend
  ports:
    - port: 5000
